### ISSUE TITLE
Erroneous output

### ISSUE THREAD

**Issue by cphyc** [AppliedMathematicsANU/diamorse#3]
Hi,
I have a 3D dataset that I converted into netCDF3 format. Whenever I try to use it as input for the Persistence util, I get the following output:

```
# Persistence pairs for density.nc
#   format: <birth> <death> <dimension> <creator xyz> <destructor xyz>
9969209968386869046778552952102584320.000000          inf    0       0.0    0.0    0.0       -      -      -  
#
# Metadata:
#
#+ zdim_total
#= 74
#
#+ total_grid_size_xyz
#= 74, 74, 74
#
#+ number_of_files
#= 1
#
#+ dataset_id
#= 20160929_130305_persistencedensity_GVF_PP
#
#+ history_20160929_124419_vector_fielddensity_GVF
#= {
#=   "id": "20160929_124419_vector_fielddensity_GVF",
#=   "process": "Discrete Morse Gradient Vector Field",
#=   "sourcefile": "VectorField.C",
#=   "revision": {
#=     "id": "83d23e8cdfbd1fd378f521c85781699ef94981b5",
#=     "date": "2016-06-07 20:12:12 +1000"
#=   },
#=   "parent": "density",
#=   "predecessors": [
#=     "density"
#=   ],
#=   "parameters": {
#=   }
#= }
#
#+ zdim_range
#= 0, 73
#
#+ history_20160929_130305_persistencedensity_GVF_PP
#= {
#=   "id": "20160929_130305_persistencedensity_GVF_PP",
#=   "process": "Critical Cell Persistence Pairs",
#=   "sourcefile": "PersistencePairs.C",
#=   "revision": {
#=     "id": "83d23e8cdfbd1fd378f521c85781699ef94981b5",
#=     "date": "2016-06-07 20:12:12 +1000"
#=   },
#=   "parent": "20160929_124419_vector_fielddensity_GVF",
#=   "predecessors": [
#=     "20160929_124419_vector_fielddensity_GVF",
#=     "density"
#=   ],
#=   "parameters": {
#=   }
#= }
```

To me, it looks like my dataset's header was correctly parsed (it has 74_74_74 cells), but the values seem to be erroneous. 

Do you have any idea?

**Comment by cphyc** [comment]
I attached the field I am using as input. The original version is the hdf5 version, and I converted it into netCDF3 format.
[density.zip](https://github.com/AppliedMathematicsANU/diamorse/files/500714/density.zip)

**Comment by odf** [comment]
It seems that the NetCDF file has no data in it, i.e. all values are 0.

**Comment by cphyc** [comment]
Hi, that's correct the file was empty. I fixed this, but now I get the error:

    VectorField: ../lib/netcdf.hpp:832: anu_am::netcdf::Header anu_am::netcdf::BufferStream<Buffer>::readHeader() [with Buffer = anu_am::netcdf::FileBuffer]: Assertion `std::string(magic.begin(), magic.end()) == "CDF\x1"' failed.
    Aborted (core dumped)

Once again, the file is attached.
[density.zip](https://github.com/AppliedMathematicsANU/diamorse/files/506147/density.zip)

**Comment by cphyc** [comment]
Thanks you for the help. It was effectively that.
