### ISSUE TITLE
Support for 4D?

### ISSUE THREAD

**Issue by cphyc** [AppliedMathematicsANU/diamorse#4]
Hi,
is there any way to adapt your code to 4D?

**Comment by odf** [comment]
There certainly are ways, but it would require some effort. Most of the core algorithms are implemented in a generic way (e.g. the dimension being a variable), but our main data structures, specifically `CubicalComplex` (including helper classes such as `Facets`), `MorseVectorField`, `VertexMap` and `PackedMap` are all optimised for 3D. So the first step would be to add 4d implementations for these that expose a compatible public API. Then there are quite a few places, including input/output, the Python wrappers and probably others, where 3d is assumed to keep the code simple. I'd say that individually most of the changes required are fairly easy, but on the whole it's not exactly something I would attempt over a weekend.

**Comment by cphyc** [comment]
Thanks for your reply. I'm going to dive in the code to try to get an estimate of the time required for extending the capabilities to 4D.
