### ISSUE TITLE
Cannot compile against anaconda

### ISSUE THREAD

**Issue by michiexile** [AppliedMathematicsANU/diamorse#6]
I tried installing and using `diamorse`, and got the following result from my first attempt in creating the python bindings:

```
[m.johansson@penzias diamorse]$ make python
make -C src/python
make[1]: Entering directory `/scratch/m.johansson/diamorse/src/python'
cython --cplus MorseAnalysis.pyx
g++ -std=c++11 -g -O3 -Wno-cpp -I /share/usr/compilers/python/anaconda/4.3.0_1/include/python2.7 -I /share/usr/compilers/python/anaconda/4.3.0_1/lib/python2.7/site-packages/numpy/core/include -I ../lib --shared -fPIC MorseAnalysis.cpp -o ../../bin/MorseAnalysis.so -lpython2.7
/usr/bin/ld: cannot find -lpython2.7
collect2: error: ld returned 1 exit status
make[1]: *** [../../bin/MorseAnalysis.so] Error 1
rm MorseAnalysis.cpp
make[1]: Leaving directory `/scratch/m.johansson/diamorse/src/python'
make: *** [python] Error 2
```

I tried changing `diamorse/src/python/Makefile` from
```
LDFLAGS     = -lpython${PYTHON_VERSION}
```
to
```
LDFLAGS     = -L ${PYTHON_PREFIX}/lib -lpython${PYTHON_VERSION}
```

After this change, the build went through, but `persistence.py` still doesn't work:
```
[m.johansson@penzias ~]$ PYTHONPATH=$PYTHONPATH:/scratch/m.johansson/diamorse/python/ time diamorse/python/persistence.py tomo_floatfoo_IMP.nc -r > foo.txt
Traceback (most recent call last):
  File "diamorse/python/persistence.py", line 4, in <module>
    from MorseAnalysis import VolumeImage, VectorField
ImportError: /scratch/m.johansson/diamorse/python/MorseAnalysis.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz
0.01user 0.01system 0:00.05elapsed 55%CPU (0avgtext+0avgdata 5456maxresident)k
0inputs+0outputs (0major+1864minor)pagefaults 0swaps
```

**Comment by odf** [comment]
Unfortunately, I have no experience with Anaconda, at all. Google results for "throw_out_of_range" seem to indicate that their might be a version mismatch between your g++ compiler and your python executable (specifically, I think, which versions of the standard libraries they link to).

Thanks for reporting this, and let use know if you can figure it out, especially if it looks like an issue other Anaconda users are likely to come across.

**Comment by chulmoon** [comment]
I am not sure it is because of Anaconda, but I had the same issue and solved by installing the package:

For Fedora/RHEL
`
yum install python-devel
`

For Ubuntu
`
apt-get install python-dev
`

**Comment by odf** [comment]
@chulmoon Thanks for that!
